---
version: '3'
services:
  db:
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
  web:
    command: >
      bash -c "/mastermind-hub/bin/rails db:test:prepare
      && /mastermind-hub/bin/rails spec"
    volumes:
      - ./app:/mastermind-hub/app
      - ./bin:/mastermind-hub/bin
      - ./config:/mastermind-hub/config
      - ./db:/mastermind-hub/db
      - ./spec:/mastermind-hub/spec
      - ./public:/mastermind-hub/public
    depends_on:
      - db
    expose:
      - "3000"
    environment:
      - APPLICATION_HOST=host
      - RAILS_ENV=test
      - PGHOST=localhost
      - PGUSER=postgres
      - PGPASSWORD=postgres
    image: mastermind-hub:latest
    ports:
      - 3000:3000
  selenium-hub:
    image: selenium/hub:latest
    container_name: selenium-hub
    ports:
      - 4444:4444
  chrome:
    image: selenium/node-chrome:latest
    depends_on:
      - selenium-hub
    environment:
      - HUB_HOST=selenium-hub
      - HUB_PORT=4444
