---
version: '3'
services:
  db:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
  web:
    command: ["/mastermind-hub/bin/rails", "server", "--port=3000", "--binding=0.0.0.0"]
    volumes:
      - ./app:/mastermind-hub/app
      - ./bin:/mastermind-hub/bin
      - ./config:/mastermind-hub/config
      - ./db:/mastermind-hub/db
      - ./public:/mastermind-hub/public
    depends_on:
      - db
    expose:
      - "3000"
    environment:
      - APPLICATION_HOST='localhost:3000'
    image: mastermind-hub:latest
    ports:
      - 3000:3000
