---
version: '3'

networks:
  mastermind-net:

services:
  db:
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    networks:
      - mastermind-net

  web:
    command: bash -c "rails db:test:prepare && rails spec"
    volumes:
      - ./app:/mastermind-hub/app
      - ./bin:/mastermind-hub/bin
      - ./config:/mastermind-hub/config
      - ./db:/mastermind-hub/db
      - ./spec:/mastermind-hub/spec
      - ./public:/mastermind-hub/public
    depends_on:
      - db
      - chrome
    tty: true
    environment:
      - APPLICATION_HOST=host
      - PGHOST=localhost
      - PGPASSWORD=postgres
      - PGUSER=postgres
      - RAILS_ENV=test
      - RUBYOPT=-W:no-deprecated
      - SELENIUM_HOST=selenium-hub
      - SELENIUM_PORT=4444
      - TEST_APP_HOST=web
      - TEST_PORT=3000
    image: mastermind-hub:latest
    ports:
      - 3000:3000
      - 3001:3001
    networks:
      mastermind-net:
        aliases:
          - mastermind-hub.com

  selenium-hub:
    image: selenium/hub:latest
    container_name: selenium-hub
    ports:
      - 4444:4444
      - 5900:5900
    networks:
      - mastermind-net

  chrome:
    image: selenium/node-chrome:latest
    volumes:
      - /dev/shm:/dev/shm
    depends_on:
      - selenium-hub
    environment:
      - HUB_HOST=selenium-hub
      - HUB_PORT=4444
    networks:
      - mastermind-net
