default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: mastermind_hub_development

test:
  <<: *default
  database: mastermind_hub_test

production:
  <<: *default
  database: mastermind_hub_production
  username: mastermind_hub
  password: <%= ENV['MASTERMIND_HUB_DATABASE_PASSWORD'] %>
